name: Place Tux CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
          cache: "pip"

      - name: Install requirements for everything
        run: |
          pip install -r overlay/requirements.txt
          pip install -r artwork_builder/requirements.txt
          pip install -r coord_gen/requirements.txt

      - name: Build tux_raw.png
        run: cp ./artwork/tux/tux.png ./.build/tux_raw.png

      - name: Build tux_coords.png
        run: python coord_gen/coords.py --input ./artwork/tux/tux.png --output ./.build/tux_coords.png

      - name: Build tux_combined_all.png
        run: |
          cd artwork_builder
          python gen_overlay_from_sources.py build_all.json
          cd ..

      - name: Build tux_overlay.png
        run: |
          cd overlay
          cp ../.build/tux_combined_all.png ./overlay_raw.png
          python explode_overlay.py
          cp ./out/overlay.png ../.build/tux_overlay.png
          cd ..

      - name: Update hash
        run: echo $(git rev-parse "$GITHUB_SHA") > ./.build/bot_hash

      - uses: EndBug/add-and-commit@v9
        with:
          add: "./.build"

      - name: Push changes
        # This will fail if no changes were made
        continue-on-error: true
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build/
          keep_files: true
          full_commit_message: deploy image
